spring:
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always # 日志打印彩色
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans